export class MsSqlConstants {
	static readonly SEQUELIZE_PROVIDER = 'SEQUELIZE_PROVIDER';

	// // EMPLOYEES MODELS
	static readonly EMPLOYEES_BASIC_INFO_MODEL = 'EMPLOYEES_BASIC_INFO_MODEL';
	static readonly EMPLOYEES_CERTIFICATION_MAPPING_MODEL = 'EMPLOYEES_CERTIFICATION_MAPPING_MODEL';
	static readonly EMPLOYEES_MONTHLY_PERFORMANCE_INFO_MODEL = 'EMPLOYEES_MONTHLY_PERFORMANCE_INFO_MODEL';
	static readonly EMPLOYEES_PROJECT_MAPPING_MODEL = 'EMPLOYEES_PROJECT_MAPPING_MODEL';
	static readonly EMPLOYEES_ROLES_MODEL = 'EMPLOYEES_ROLES_MODEL';
	static readonly EMPLOYEES_SKILL_MAPPING_MODEL = 'EMPLOYEES_SKILL_MAPPING_MODEL';

	// LOGS MODELS
	static readonly LOGS_APP_SESSIONS_MODEL = 'LOGS_APP_SESSIONS_MODEL';
	static readonly LOGS_EMAIL_LOGS_MASTER = 'LOGS_EMAIL_LOGS_MASTER';

	// // MASTER MODELS
	static readonly MASTER_CERTIFICATIONS_MODEL = 'MASTER_CERTIFICATIONS_MODEL';
	static readonly MASTER_DESIGNATION_MODEL = 'MASTER_DESIGNATION_MODEL';
	static readonly MASTER_PROJECTS_MODEL = 'MASTER_PROJECTS_MODEL';
	static readonly MASTER_ROLES_MODEL = 'MASTER_ROLES_MODEL';
	static readonly MASTER_SKILL_MODEL = 'MASTER_SKILL_MODEL';

	// // READONLY MODELS
	static readonly READONLY_9BOX_POSITIONS_MODEL = 'READONLY_9BOX_POSITIONS_MODEL';
	static readonly READONLY_CERTIFICATION_PROVIDER_MODEL = 'READONLY_CERTIFICATION_PROVIDER_MODEL';
	static readonly READONLY_DEPARTMENT_MODEL = 'READONLY_DEPARTMENT_MODEL';
	static readonly READONLY_SKILL_TAGS_MODEL = 'READONLY_SKILL_TAGS_MODEL';
}
