export enum DataType {
	UNIQUEIDENTIFIER = 'UNIQUEIDENTIFIER',
	BIGINT = 'BIGINT',
	VARCHAR = 'VARCHAR',
	INT = 'INT',
	TINYINT = 'TINYINT',
	BIT = 'BIT',
	DATE = 'DATE',
	DECIMAL = 'DECIMAL',
	SMALLINT = 'SMALLINT',
	TEXT = 'TEXT'
}
